### ISSUE TITLE
Module parse failed: node_modules/react-attr-converter/map.json Unexpected token (2:10)

### ISSUE THREAD

**Issue by dearlordylord** [kadira-samples/react-storybook-demo#17]
clone ...

npm install

npm run storybook

after lots of messages about [built] modules:

```
ERROR in ./~/react-attr-converter/map.json
Module parse failed: /Users/firfi/work/react-storybook-demo/node_modules/react-attr-converter/map.json Unexpected token (2:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:10)
    at Parser.pp$4.raise (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/firfi/work/react-storybook-demo/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/react-attr-converter/index.js 3:10-31
```

I use: 

npm 3.10.3
node 6.4.0

**Comment by thani-sh** [comment]
I also got this error when I used a custom wepack config file. I got it after updating all node modules.

**Comment by vcanales** [comment]
Hi,

check [this](https://github.com/webpack/webpack/issues/965) out.

```terminal
$ npm install json-loader
```

In webpack config:
```javascript
loaders: [
      {
        test: /\.json$/,
        loader: "json-loader",
      },
]
```

**Comment by arunoda** [comment]
This is working with this example.

@mnmtanish if we introduce a custom webpack config, we need to add a JSON if not there.
Anyway, we could also extend our config too.
See here: https://getstorybook.io/docs/react-storybook/configurations/custom-webpack-config
